CREATE DATABASE FormAuto;
USE FormAuto;

CREATE TABLE Proprietario(
    id INT NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE Mensagens(
    id INT NOT NULL,
    email_prop VARCHAR(255) NOT NULL,
    email_dstny VARCHAR(255) NOT NULL,
    nome_dstny VARCHAR(255) NOT NULL,
    msg_dstny VARCHAR(255) NOT NULL
);

ALTER TABLE Proprietario ADD PRIMAREY KEY (id);

ALTER TABLE Mensagens ADD PRIMAREY KEY (id)

ALTER TABLE Proprietario ADD KEY (email)

ALTER TABLE Mensagens ADD KEY (email_prop)

ALTER TABLE Proprietario MODIFY COLUMN id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE Mensagens MODIFY COLUMN id INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE mensagens ADD CONSTRAINT FOREIGN KEY (email_prop) REFERENCES proprietario (email)